name: Deploy site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
      # Clone repository
      - uses: actions/checkout@v3

      # Grab deno
      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # Build site
      - name: Build site
        run: deno task build --location=https://rottencandy.github.io

      # Push to site repo
      - name: Push to repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '_site'
          destination-github-username: 'rottencandy'
          destination-repository-name: 'rottencandy.github.io'
          target-branch: 'master'
          user-email: md.saud020@gmail.com
